// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNyFqQ0azwSX4i0jlCcBz8kv72owSNaM',
    appId: '1:930323550079:web:7855de5506dbae1177144a',
    messagingSenderId: '930323550079',
    projectId: 'kbc-yt-4fdc6',
    authDomain: 'kbc-yt-4fdc6.firebaseapp.com',
    storageBucket: 'kbc-yt-4fdc6.firebasestorage.app',
    measurementId: 'G-8N4F76FQW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqb63OS4hPFqD7EPjDwBMOtuTKUgQyrpY',
    appId: '1:930323550079:android:9f6e636f11ec104d77144a',
    messagingSenderId: '930323550079',
    projectId: 'kbc-yt-4fdc6',
    storageBucket: 'kbc-yt-4fdc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCxRQ_VVCI3JS6IVTLH0A8Ne_G2lJi0Sg',
    appId: '1:930323550079:ios:cda6c1459221a40177144a',
    messagingSenderId: '930323550079',
    projectId: 'kbc-yt-4fdc6',
    storageBucket: 'kbc-yt-4fdc6.firebasestorage.app',
    androidClientId: '930323550079-iemmsk95tao1ap17p07pvnbimccov0sf.apps.googleusercontent.com',
    iosClientId: '930323550079-8s386aoktqs7d7vsd410b8t896897q4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.kbcAppYt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCxRQ_VVCI3JS6IVTLH0A8Ne_G2lJi0Sg',
    appId: '1:930323550079:ios:cda6c1459221a40177144a',
    messagingSenderId: '930323550079',
    projectId: 'kbc-yt-4fdc6',
    storageBucket: 'kbc-yt-4fdc6.firebasestorage.app',
    androidClientId: '930323550079-iemmsk95tao1ap17p07pvnbimccov0sf.apps.googleusercontent.com',
    iosClientId: '930323550079-8s386aoktqs7d7vsd410b8t896897q4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.kbcAppYt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCNyFqQ0azwSX4i0jlCcBz8kv72owSNaM',
    appId: '1:930323550079:web:9a19fe1d4232a23477144a',
    messagingSenderId: '930323550079',
    projectId: 'kbc-yt-4fdc6',
    authDomain: 'kbc-yt-4fdc6.firebaseapp.com',
    storageBucket: 'kbc-yt-4fdc6.firebasestorage.app',
    measurementId: 'G-L3SWTX307N',
  );
}
